#version 440 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct DrawArraysIndirectCommand
{
	uint count;
	uint instanceCount;
	uint first;
	uint baseInstance;
};

layout(std430, binding = 5) readonly buffer ParticleCounterBuffer
{
	uint aliveCount;
	uint spawnedCountThisFrame;
	uint totalSpawnCount;
	uint reserved;
};

layout(std430, binding = 6) buffer ParticleDrawIndirectBuffer
{
	DrawArraysIndirectCommand drawCommand;
};

void main()
{
	drawCommand.instanceCount = aliveCount;
	drawCommand.baseInstance = 0u;
}
