#ifndef __PHYSICSCONSTANTS_H__
#define __PHYSICSCONSTANTS_H__

#define PHYSICS_TICKS_PER_SECOND 60
#define PHYSICS_TICK_DELTA_TIME 1.f / PHYSICS_TICKS_PER_SECOND
#define PHYSICS_DEFAULT_MAX_CONTACTS 8192
#define PHYSICS_DEFAULT_ITEARATIONS 0
#define PHYSICS_COLLISION_EPSILON 0.001f

#define DEFAULT_GRAVITATIONAL_FORCE_MAGNITUDE 9.81f
#define DEFAULT_GRAVITATIONAL_FORCE Vector3::UpVector * -DEFAULT_GRAVITATIONAL_FORCE_MAGNITUDE

#endif